version: "2"

services:
  engine:
    image: qlikea/engine:community_version
    restart: always
    command: -S AcceptEULA=${ACCEPT_EULA}
    ports:
      - "19076:9076"
    volumes: 
      - ./data:/data
