version: 2
jobs:
  build:
    docker:
      - image: node:8
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: Install dependencies
          command:
            npm install --quiet
      - run:
          name: Run ESLint
          command:
            npm run lint
      - run:
          name: Login to Docker
          command: docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD"
      - run:
          name: Install Docker Compose
          command: |
            set -x
            curl -L https://github.com/docker/compose/releases/download/1.11.2/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
            chmod +x /usr/local/bin/docker-compose
      - setup_remote_docker
      - run:
          name: Run test for hello-engine
          command: |
            set -x
            cd hello-engine
            npm install --quiet
            docker-compose up -d
            ./test.sh
