version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: Install dependencies
          command:
            npm install --quiet
      - run:
          name: Run ESLint
          command:
            npm run lint
      - setup_remote_docker
      - run:
          name: Login to Docker
          command: docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD"
      - run:
          name: Run test for hello-engine
          command: |
            set -x
            cd hello-engine
            npm install --quiet
            docker-compose up -d
            ./test.sh
