version: 2
jobs:
  build:
    docker:
      - image: node:8
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: Install dependencies
          command:
            npm install --quiet
